### ISSUE TITLE
There are some problems in the x64 program of win10

### ISSUE THREAD

**Issue by icyfox168168** [AmJayden/custom-VEH#1]
X86 program is running normally

X64 program running abnormally

Compiler uses vs2022

Infinite loop
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!
c0000005 is handled!

**Comment by AmJayden** [comment]
Sorry for the late response.
Can you provide the code for your callback and what you're trying to do?

If the handler is being ran it could be an issue within your callback, it might be throwing an exception within itself.
Also I plan on totally revamping this within next week, any problems should be fixed by then.

**Comment by icyfox168168** [comment]
I run the example provided by the program

**Comment by icyfox168168** [comment]
Do you have time to update?

**Comment by AmJayden** [comment]
I've rewritten the entire project to use my "ud" utility library and it's been tested pretty thoroughly on my machine with both x86 and x64.
